service: aws-swapi
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-west-2
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-west-2:877368439791:table/UserTable

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  getDataFromSWAPI:
    handler: src/SWAPI/getData.getDataFromSWAPI
    events:
      - httpApi:
          path: /getPersonFromSWAPI/{id}
          method: get
  createUser:
    handler: src/AWS/createUser.createUser
    events:
      - httpApi:
          path: /createUser
          method: post
  getUsers:
    handler: src/AWS/getUsers.getUsers
    events:
      - httpApi:
          path: /getUsers
          method: get
  getUser:
    handler: src/AWS/getUser.getUser
    events:
      - httpApi:
          path: /getUser/{id}
          method: get
  updateUser:
    handler: src/AWS/updateUser.updateUser
    events:
      - httpApi:
          path: /updateUser/{id}
          method: put
  deleteUser:
    handler: src/AWS/deleteUser.deleteUser
    events:
      - httpApi:
          path: /deleteUser/{id}
          method: delete

resources:
  Resources:
    UserTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UserTable
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions: 
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
